# Generated by Django 2.1.3 on 2020-04-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Customer Username')),
                ('email', models.CharField(max_length=50, verbose_name='Customer Email')),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=1200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Us Request',
                'verbose_name_plural': 'Contact Us Requests',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32, verbose_name='Full name')),
                ('lname', models.CharField(max_length=32, verbose_name='Last name')),
                ('mname', models.CharField(blank=True, max_length=32, null=True, verbose_name='Middle name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('score', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rank')),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='main/img/profile_images/default_avatar.jpg', unique=True, upload_to='main/img/profile_images/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
