# Generated by Django 2.1.3 on 2020-04-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200405_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created'], 'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
    ]
