# Generated by Django 2.1.3 on 2020-04-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200405_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
    ]
