# Generated by Django 2.1.3 on 2020-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200406_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='main/avatars/default_avatar.jpg', null=True, unique=True, upload_to='media/profile_pics'),
        ),
    ]
